architecture: CNN-Glyph


dataset: data/simple-star-XL.zip
test: data/simple-star-test-XL.zip


epochs: 50
batch_size: 2048
learning_rate: 0.0001
loss_fn: MSELoss
optimizer: Adam
cuda: 0
name: default_run

image_resolution: [128, 128]

regression: true
num_bins: 50
num_pairs: 20480
margin: 5.0
max_distance: 25.0
maxdistance_decay: 1.0
margin_decay: 1.0

rotation: 0
translation_x: 0
translation_y: 0

stepsize: 1
learning_decay: 0.85

stride: 0

seed: 42

hydra:
  output_subdir: null
  job:
    chdir: false
  run:
    dir: .