architecture: CNN-Glyph


dataset: data/simple-star-L.zip
test: data/simple-star-test.zip


epochs: 20
batch_size: 2048
learning_rate: 0.0005
loss_fn: MSELoss
optimizer: Adam
cuda: 0
name: default_run

image_resolution: [128, 128]

regression: true
num_bins: 5
num_pairs: 20480
margin: 15.0
max_distance: 20.0
maxdistance_decay: 1.0
margin_decay: 1.0

rotation: 0
translation_x: 0
translation_y: 0

stepsize: 1
learning_decay: 1.0

stride: 0

hydra:
  output_subdir: null
  job:
    chdir: false
  run:
    dir: .